variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

build:
  image: fmorgner/cevelop-plugin-build:latest
  stage: build
  cache:
    key: "ILTISCppMavenCache"
    paths:
      - ./.m2/repository
  script:
    - mvn compile
  artifacts:
    paths:
      - ./**/target/*

test:
  image: fmorgner/cevelop-plugin-build:latest
  stage: test
  cache:
    key: "ILTISCppMavenCache"
    paths:
      - ./.m2/repository
    policy: pull
  script:
    - 'xvfb-run --server-args="-screen 0 1024x768x24" mvn verify -Djarsigner.skip=true'
