stages:
  - build and test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

.deployScript: &DEPLOY_SCRIPT
  before_script:
    - cd ILTISCoreProject
  script:
    - eval $(ssh-agent -s)
    - echo "$P2_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "$P2_HOST_KEY" > ~/.ssh/known_hosts'
    - 'ssh hudson@cute-test.com "cd /var/www/iltis && mkdir -p ${UPDATE_SITE}"'
    - 'scp -r releng/ch.hsr.ifs.iltis.core.update/target/repository/* hudson@cute-test.com:/var/www/iltis/${UPDATE_SITE}'
    - 'ssh hudson@cute-test.com "cd /var/www/iltis && compile-composite-updatesite  ILTIS 0.1.0"'

build-signed:
  image: gitlab.dev.ifs.hsr.ch:45023/cevelop/docker-tycho-release:latest
  stage: build and test
  cache:
    key: "ILTISCoreMavenCache"
    paths:
      - .m2/repository
  script:
    - 'xvfb-run ./build clean package -s'
  artifacts:
    paths:
      - ./*/*/*/target/repository/**
  only:
    - master
    - develop

deploy master:
  image: gitlab.dev.ifs.hsr.ch:45023/ifs/docker-alpine-ssh:latest
  stage: deploy
  variables:
    UPDATE_SITE: core
  only:
    - master
  <<: *DEPLOY_SCRIPT

deploy develop:
  image: gitlab.dev.ifs.hsr.ch:45023/ifs/docker-alpine-ssh:latest
  stage: deploy
  variables:
    UPDATE_SITE: core-unstable
  only:
    - develop
  <<: *DEPLOY_SCRIPT
