#=============================================================================#
# General configuration                                                       #
#=============================================================================#

stages:
  - build and test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_SUBMODULE_STRATEGY: "recursive"
  P2_SOURCE: "releng/ch.hsr.ifs.iltis.testing.core.update/target/repository"
  P2_DESTINATION: "testing-core"

#=============================================================================#
# Build jobs                                                                  #
#=============================================================================#

build signed:
  image: gitlab.dev.ifs.hsr.ch:45023/cevelop/docker-tycho-release:latest
  stage: build and test
  cache:
    key: "ILTISTestingCoreMavenCache"
    paths:
      - .m2/repository
  script:
    - 'xvfb-run ./tools/build clean verify -s'
  artifacts:
    paths:
      - ./*/*/*/target/repository/**
  only:
    - master
    - develop

build unsigned:
  image: gitlab.dev.ifs.hsr.ch:45023/cevelop/docker-tycho-build:latest
  stage: build and test
  cache:
    key: "ILTISTestingCoreMavenCache"
    paths:
      - .m2/repository
  script:
    - 'xvfb-run ./tools/build clean verify'
  except:
    - master
    - develop

#=============================================================================#
# Deployment jobs                                                             #
#=============================================================================#

.deployCommon: &DEPLOY_COMMON
  image: gitlab.dev.ifs.hsr.ch:45023/ifs/docker-alpine-ssh:latest
  cache: {}
  stage: deploy
  dependencies:
    - build signed
  script:
    - "cd ILTISTestingCoreProject"
    - "../tools/ci/deploy"

deploy development:
  <<: *DEPLOY_COMMON
  variables:
    P2_ROOT: "/var/www/iltis-unstable"
  only:
    - develop

deploy release:
  <<: *DEPLOY_COMMON
  variables:
    P2_ROOT: "/var/www/iltis"
  only:
    - master
