#=============================================================================#
# General configuration                                                       #
#=============================================================================#

stages:
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_SUBMODULE_STRATEGY: "normal"
  P2_COMPOSITE_ENABLE: "1"
  P2_COMPOSITE_NAME: "ILTIS"
  P2_DESTINATION: "testing-core"
  P2_SOURCE: "./ILTISTestingCoreProject/releng/ch.hsr.ifs.iltis.testing.core.update/target/repository"

#=============================================================================#
# Build jobs                                                                  #
#=============================================================================#

.buildCommon: &BUILD_COMMON
  stage: build
  script:
    - './tools/build clean verify ${BUILD_FLAGS}'
  cache:
    key: "maven-$CI_PROJECT_ID"
    paths:
      - ".m2/repository"
    policy: pull-push


Build Signed:
  <<: *BUILD_COMMON
  image: gitlab.dev.ifs.hsr.ch:45023/cevelop/docker-tycho-release:latest
  only:
    - master
    - develop
    - /^release\/.*$/
  variables:
    BUILD_FLAGS: "--sign"
  artifacts:
    paths:
      - ./*/*/*/target/repository/**

Build Unsigned:
  <<: *BUILD_COMMON
  image: gitlab.dev.ifs.hsr.ch:45023/cevelop/docker-tycho-build:latest
  except:
    - master
    - develop
    - /^release\/.*$/

#=============================================================================#
# Deployment jobs                                                             #
#=============================================================================#

Deploy:
  stage: deploy
  image: gitlab.dev.ifs.hsr.ch:45023/ifs/docker-alpine-ssh:latest
  cache: {}
  only:
    - develop
    - master
  dependencies:
    - Build Signed
  variables:
    - P2_ROOT: "/var/www/iltis$( (echo ${CI_COMMIT_REF_NAME} | grep develop &>/dev/null) && echo '-unstable')"
    - P2_COMPOSITE_VERSION: "sed -n 's/<version>\([0-9]\.[0-9]\.[0.9]\)<\/version>/\1/p' *Project/pom.xml"
  script:
    - "tools/ci/deploy"
