variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

image: fmorgner/cevelop-plugin-build:latest

build:
  stage: build
  cache:
    key: "ILTISCoreMavenCache"
    paths:
      - ./.m2/repository
  script:
    - mvn compile
  artifacts:
    paths:
      - ./**/target/*

test:
  stage: test
  cache:
    key: "ILTISCoreMavenCache"
    paths:
      - ./.m2/repository
    policy: pull
  script:
    - 'xvfb-run --server-args="-screen 0 1024x768x24" mvn verify -Djarsigner.skip=true'
  artifacts:
    paths:
      - ./ch.hsr.ifs.iltis.core.update/target/repository/*

deploy:
  stage: deploy
  cache:
    key: "ILTISCoreMavenCache"
    paths:
      - ./.m2/repository
    policy: pull
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$P2_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "$P2_HOST_KEY" > ~/.ssh/known_hosts'
    - 'ssh hudson@cute-test.com "cd /var/www/iltis && mkdir -p core"'
    - 'scp -r ch.hsr.ifs.iltis.core.update/target/repository/* hudson@cute-test.com:/var/www/iltis/core'
    - 'ssh hudson@cute-test.com "cd /var/www/iltis && compile-composite-updatesite  ILTIS 0.1.0"'
